name: deuterium
channels:
  - defaults
  - conda-forge
  - symengine
dependencies:
  - pip
  - numpy
  - sympy
  - matplotlib
  - scikit-image
  - seaborn
  - scikit-learn
  - mypy
  - black
  - pytest
  - jupyterlab
  - python-symengine
